-- MySQL Script generated by MySQL Workbench
-- 04/27/16 13:03:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema beerFans
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beerFans
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beerFans` DEFAULT CHARACTER SET utf8 ;
USE `beerFans` ;

-- -----------------------------------------------------
-- Table `beerFans`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sortname` VARCHAR(4) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`, `country_id`),
  INDEX `fk_states_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_states_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `beerFans`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`producerType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`producerType` (
  `idProducerType` INT NOT NULL AUTO_INCREMENT,
  `producerTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducerType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`producer` (
  `idProducer` INT NOT NULL AUTO_INCREMENT,
  `producerName` VARCHAR(45) NOT NULL,
  `producerDescription` VARCHAR(560) NOT NULL,
  `producerAddress` VARCHAR(150) NOT NULL,
  `producerZip` VARCHAR(8) NOT NULL,
  `producerPhone` VARCHAR(20) NOT NULL,
  `producerEmail` VARCHAR(45) NOT NULL,
  `producerProfileImage` VARCHAR(450) NOT NULL,
  `producerCoverImage` VARCHAR(450) NOT NULL,
  `producerSite` VARCHAR(450) NULL,
  `producerFacebook` VARCHAR(450) NULL,
  `producerTwitter` VARCHAR(450) NULL,
  `producerInstagram` VARCHAR(450) NULL,
  `country_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `idProducerType` INT NOT NULL,
  PRIMARY KEY (`idProducer`, `country_id`, `state_id`, `idProducerType`),
  INDEX `fk_producer_countries1_idx` (`country_id` ASC),
  INDEX `fk_producer_states1_idx` (`state_id` ASC),
  INDEX `fk_producer_producerType1_idx` (`idProducerType` ASC),
  CONSTRAINT `fk_producer_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `beerFans`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producer_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `beerFans`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producer_producerType1`
    FOREIGN KEY (`idProducerType`)
    REFERENCES `beerFans`.`producerType` (`idProducerType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`beerSlider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`beerSlider` (
  `idSlider` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idSlider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`beerType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`beerType` (
  `idBeerType` INT NOT NULL AUTO_INCREMENT,
  `beerTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBeerType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`beer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`beer` (
  `idBeer` INT NOT NULL AUTO_INCREMENT,
  `beerName` VARCHAR(45) NOT NULL,
  `beerDescription` VARCHAR(560) NOT NULL,
  `beerStrength` VARCHAR(45) NOT NULL,
  `beerIBUS` VARCHAR(45) NOT NULL,
  `beerProfileImage` VARCHAR(450) NOT NULL,
  `beerCoverImage` VARCHAR(450) NOT NULL,
  `beerBottleImage` VARCHAR(450) NOT NULL,
  `beerSite` VARCHAR(450) NULL,
  `beerFacebook` VARCHAR(450) NULL,
  `beerTwitter` VARCHAR(450) NULL,
  `beerInstagram` VARCHAR(450) NULL,
  `idProducer` INT NOT NULL,
  `idSlider` INT NOT NULL,
  `idBeerType` INT NOT NULL,
  PRIMARY KEY (`idBeer`, `idProducer`, `idSlider`, `idBeerType`),
  INDEX `fk_beer_producer_idx` (`idProducer` ASC),
  INDEX `fk_beer_beerSlider1_idx` (`idSlider` ASC),
  INDEX `fk_beer_beerType1_idx` (`idBeerType` ASC),
  CONSTRAINT `fk_beer_producer`
    FOREIGN KEY (`idProducer`)
    REFERENCES `beerFans`.`producer` (`idProducer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_beer_beerSlider1`
    FOREIGN KEY (`idSlider`)
    REFERENCES `beerFans`.`beerSlider` (`idSlider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_beer_beerType1`
    FOREIGN KEY (`idBeerType`)
    REFERENCES `beerFans`.`beerType` (`idBeerType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`bannerBeerSlider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`bannerBeerSlider` (
  `idBannerBeerSlider` INT NOT NULL AUTO_INCREMENT,
  `bannerImage` VARCHAR(450) NOT NULL,
  `idSlider` INT NOT NULL,
  PRIMARY KEY (`idBannerBeerSlider`, `idSlider`),
  INDEX `fk_bannerBeerSlider_beerSlider1_idx` (`idSlider` ASC),
  CONSTRAINT `fk_bannerBeerSlider_beerSlider1`
    FOREIGN KEY (`idSlider`)
    REFERENCES `beerFans`.`beerSlider` (`idSlider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`, `state_id`),
  INDEX `fk_cities_states1_idx` (`state_id` ASC),
  CONSTRAINT `fk_cities_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `beerFans`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`rawMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`rawMaterial` (
  `idRawMaterial` INT NOT NULL AUTO_INCREMENT,
  `rawMaterialName` VARCHAR(45) NOT NULL,
  `rawMaterialGeneralDescription` VARCHAR(560) NOT NULL,
  `rawMaterialDescription` VARCHAR(560) NOT NULL,
  `rawMaterialDescriptionHTML` VARCHAR(1260) NOT NULL,
  `rawMaterialLatitude` VARCHAR(45) NULL,
  `rawMaterialLongitude` VARCHAR(45) NULL,
  `rawMaterialAddress` VARCHAR(150) NOT NULL,
  `rawMaterialZip` VARCHAR(8) NOT NULL,
  `rawMaterialPhone` VARCHAR(20) NOT NULL,
  `rawMaterialEmail` VARCHAR(45) NOT NULL,
  `rawMaterialProfileImage` VARCHAR(450) NOT NULL,
  `rawMaterialCoverImage` VARCHAR(450) NOT NULL,
  `rawMaterialSite` VARCHAR(450) NULL,
  `rawMaterialFacebook` VARCHAR(450) NULL,
  `rawMaterialTwitter` VARCHAR(450) NULL,
  `rawMaterialInstagram` VARCHAR(450) NULL,
  PRIMARY KEY (`idRawMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`rawMaterialType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`rawMaterialType` (
  `idDrawMaterialType` INT NOT NULL AUTO_INCREMENT,
  `rawMaterialTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDrawMaterialType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`rawMaterial_has_rawMaterialType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`rawMaterial_has_rawMaterialType` (
  `idRawMaterial` INT NOT NULL,
  `idDrawMaterialType` INT NOT NULL,
  PRIMARY KEY (`idRawMaterial`, `idDrawMaterialType`),
  INDEX `fk_rawMaterial_has_rawMaterialType_rawMaterialType1_idx` (`idDrawMaterialType` ASC),
  INDEX `fk_rawMaterial_has_rawMaterialType_rawMaterial1_idx` (`idRawMaterial` ASC),
  CONSTRAINT `fk_rawMaterial_has_rawMaterialType_rawMaterial1`
    FOREIGN KEY (`idRawMaterial`)
    REFERENCES `beerFans`.`rawMaterial` (`idRawMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rawMaterial_has_rawMaterialType_rawMaterialType1`
    FOREIGN KEY (`idDrawMaterialType`)
    REFERENCES `beerFans`.`rawMaterialType` (`idDrawMaterialType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`bannerSliderHome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`bannerSliderHome` (
  `idBannerSliderHome` INT NOT NULL AUTO_INCREMENT,
  `bannerSliderHomeImage` VARCHAR(450) NOT NULL,
  `bannerSliderHomeUrl` VARCHAR(450) NULL,
  PRIMARY KEY (`idBannerSliderHome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`bannerSliderNew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`bannerSliderNew` (
  `idBannerSliderNew` INT NOT NULL AUTO_INCREMENT,
  `bannerSliderNewTitle` VARCHAR(45) NOT NULL,
  `bannerSliderNewSubtitle` VARCHAR(45) NOT NULL,
  `bannerSliderNewDescription` VARCHAR(450) NOT NULL,
  `bannerSliderNewUrl` VARCHAR(450) NOT NULL,
  `bannerSliderNewImage` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idBannerSliderNew`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`bannerSliderPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`bannerSliderPost` (
  `idBannerSliderPost` INT NOT NULL AUTO_INCREMENT,
  `bannerSliderPostTitle` VARCHAR(45) NOT NULL,
  `bannerSliderPostSubtitle` VARCHAR(45) NOT NULL,
  `bannerSliderPostDescription` VARCHAR(450) NOT NULL,
  `bannerSliderPostUrl` VARCHAR(450) NOT NULL,
  `bannerSliderPostImage` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idBannerSliderPost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`favoritesList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`favoritesList` (
  `idFavoritesList` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFavoritesList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`wishList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`wishList` (
  `idWishList` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idWishList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`ranksList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`ranksList` (
  `idRanksList` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idRanksList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`publicMessagesList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`publicMessagesList` (
  `idPublicMessagesList` INT NOT NULL,
  PRIMARY KEY (`idPublicMessagesList`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`inbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`inbox` (
  `idInbox` INT NOT NULL,
  PRIMARY KEY (`idInbox`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userLastName` VARCHAR(145) NOT NULL,
  `userBirthDate` DATE NOT NULL,
  `userDescription` VARCHAR(45) NULL,
  `userProfileImage` VARCHAR(450) NOT NULL,
  `userCoverImage` VARCHAR(450) NOT NULL,
  `userEmail` VARCHAR(245) NOT NULL,
  `userPassword` VARCHAR(45) NOT NULL,
  `userStatus` TINYINT(1) NOT NULL,
  `country_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `idFavoritesList` INT NOT NULL,
  `idWishList` INT NOT NULL,
  `idRanksList` INT NOT NULL,
  `idPublicMessagesList` INT NOT NULL,
  `idInbox` INT NOT NULL,
  PRIMARY KEY (`idUser`, `country_id`, `state_id`, `city_id`, `idFavoritesList`, `idWishList`, `idRanksList`, `idPublicMessagesList`, `idInbox`),
  INDEX `fk_user_countries1_idx` (`country_id` ASC),
  INDEX `fk_user_cities1_idx` (`city_id` ASC),
  INDEX `fk_user_states1_idx` (`state_id` ASC),
  INDEX `fk_user_favoritesList1_idx` (`idFavoritesList` ASC),
  INDEX `fk_user_wishList1_idx` (`idWishList` ASC),
  INDEX `fk_user_ranksList1_idx` (`idRanksList` ASC),
  INDEX `fk_user_publicMessagesList1_idx` (`idPublicMessagesList` ASC),
  INDEX `fk_user_inbox1_idx` (`idInbox` ASC),
  CONSTRAINT `fk_user_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `beerFans`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `beerFans`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `beerFans`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_favoritesList1`
    FOREIGN KEY (`idFavoritesList`)
    REFERENCES `beerFans`.`favoritesList` (`idFavoritesList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_wishList1`
    FOREIGN KEY (`idWishList`)
    REFERENCES `beerFans`.`wishList` (`idWishList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_ranksList1`
    FOREIGN KEY (`idRanksList`)
    REFERENCES `beerFans`.`ranksList` (`idRanksList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_publicMessagesList1`
    FOREIGN KEY (`idPublicMessagesList`)
    REFERENCES `beerFans`.`publicMessagesList` (`idPublicMessagesList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_inbox1`
    FOREIGN KEY (`idInbox`)
    REFERENCES `beerFans`.`inbox` (`idInbox`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`favoriteElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`favoriteElement` (
  `idFavoriteElement` INT NOT NULL AUTO_INCREMENT,
  `idFavoritesList` INT NOT NULL,
  `idBeer` INT NOT NULL,
  PRIMARY KEY (`idFavoriteElement`, `idFavoritesList`, `idBeer`),
  INDEX `fk_favoriteElement_favoritesList1_idx` (`idFavoritesList` ASC),
  INDEX `fk_favoriteElement_beer1_idx` (`idBeer` ASC),
  CONSTRAINT `fk_favoriteElement_favoritesList1`
    FOREIGN KEY (`idFavoritesList`)
    REFERENCES `beerFans`.`favoritesList` (`idFavoritesList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoriteElement_beer1`
    FOREIGN KEY (`idBeer`)
    REFERENCES `beerFans`.`beer` (`idBeer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`wishListElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`wishListElement` (
  `idWishListElement` INT NOT NULL AUTO_INCREMENT,
  `idWishList` INT NOT NULL,
  `idBeer` INT NOT NULL,
  PRIMARY KEY (`idWishListElement`, `idWishList`, `idBeer`),
  INDEX `fk_wishListElement_beer1_idx` (`idBeer` ASC),
  INDEX `fk_wishListElement_wishList1_idx` (`idWishList` ASC),
  CONSTRAINT `fk_wishListElement_beer1`
    FOREIGN KEY (`idBeer`)
    REFERENCES `beerFans`.`beer` (`idBeer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishListElement_wishList1`
    FOREIGN KEY (`idWishList`)
    REFERENCES `beerFans`.`wishList` (`idWishList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`ranksListElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`ranksListElement` (
  `idRanksListElement` INT NOT NULL AUTO_INCREMENT,
  `idBeer` INT NOT NULL,
  `ranksListElementRank` DOUBLE NOT NULL,
  `idRanksList` INT NOT NULL,
  PRIMARY KEY (`idRanksListElement`, `idBeer`, `idRanksList`),
  INDEX `fk_ranksListElement_beer1_idx` (`idBeer` ASC),
  INDEX `fk_ranksListElement_ranksList1_idx` (`idRanksList` ASC),
  CONSTRAINT `fk_ranksListElement_beer1`
    FOREIGN KEY (`idBeer`)
    REFERENCES `beerFans`.`beer` (`idBeer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranksListElement_ranksList1`
    FOREIGN KEY (`idRanksList`)
    REFERENCES `beerFans`.`ranksList` (`idRanksList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`postElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`postElement` (
  `idPostElement` INT NOT NULL AUTO_INCREMENT,
  `postElementComment` VARCHAR(550) NOT NULL,
  `postElementDate` DATETIME NOT NULL,
  `idPublicMessagesList` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idPostElement`, `idPublicMessagesList`, `idUser`),
  INDEX `fk_postElement_publicMessagesList1_idx` (`idPublicMessagesList` ASC),
  INDEX `fk_postElement_user1_idx` (`idUser` ASC),
  CONSTRAINT `fk_postElement_publicMessagesList1`
    FOREIGN KEY (`idPublicMessagesList`)
    REFERENCES `beerFans`.`publicMessagesList` (`idPublicMessagesList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postElement_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `beerFans`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`chat` (
  `idChat` INT NOT NULL AUTO_INCREMENT,
  `inbox_idInbox` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idChat`, `inbox_idInbox`, `user_idUser`),
  INDEX `fk_chat_inbox1_idx` (`inbox_idInbox` ASC),
  INDEX `fk_chat_user1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_chat_inbox1`
    FOREIGN KEY (`inbox_idInbox`)
    REFERENCES `beerFans`.`inbox` (`idInbox`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `beerFans`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beerFans`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beerFans`.`message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `messageText` VARCHAR(540) NOT NULL,
  `messageDate` DATETIME NOT NULL,
  `messageStatus` TINYINT(1) NOT NULL,
  `chat_idChat` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idMessage`, `chat_idChat`, `user_idUser`),
  INDEX `fk_message_chat1_idx` (`chat_idChat` ASC),
  INDEX `fk_message_user1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_idChat`)
    REFERENCES `beerFans`.`chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `beerFans`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
